### ISSUE TITLE
Refactor Trending Artist Component

### ISSUE THREAD

**Issue by aonomike** [AgileVentures/sfn-client#168]
Make the Trending Artist component reusable by implementing props
## Expected Behavior

* Have a component that has the Artist Name and the Artist Image
* Use props to display the rest of the content of  the TrendingArtist component
## Current Behavior

The data is not displayed based on props

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39):
* Operating System and version (desktop or mobile):

**Comment by javpet** [comment]
Fixed in #173

**Comment by yakryder** [comment]
The work that closed this issue is good. This issue is a step up in terms of detail from other ones I've seen. Both those things are positive. All, read further here and on #173 if you are interested in becoming a more precise communicator. 

There is disagreement between the current language of this ticket and what was actually done in #173. The `TrendingArtist` component was *removed*, not refactored. The `TrendingArtists` component as it turns out was not refactored either, but we'll get to that on the PR itself. 

`ArtistCard` can be rightly said to have been *extracted*, but it also was not refactored. You can only refactor something that already exists. 

We would like to be able to say that we refactored the Artists portion of the system to support the existence of reusable component `ArtistCard`, but as it turns out we can't even say that, as the supported causes and performances in the user-facing artist details section changed as part of #173.

Again on the word refactoring -- you cannot refactor a thing by changing its public behavior. You can only refactor the system in which that thing lives. And it is a refactor ***if and only if*** the public behavior of that system remains unchanged. 

Several extra things were done in #173 that would ideally have been clearly captured in the ticket (or not done).

**Comment by javpet** [comment]
Thanks Ryder for the comments and the detailed explanation! The issue started as a refactor because we were group thinking yesterday as we could maybe just make the component smarter as it is for multiple use cases, but then other details came like then the name doesn't fit anymore, then changing the tests accordingly as well.

**Comment by yakryder** [comment]
Perfect world the ticket would change as those things come up. Sometimes you have reviewers who are very finicky (*cough* *cough*), and if there's a gulf between the ticket and the PR you may get some friction. 

Also, if someone comes back later to investigate what motivated that PR -- let's say it causes trouble -- there's a scope divergence between the PR and the motivating issue with no record of why. 

I'm not saying that's a bad thing because it's harder to find someone to blame, but I am saying it's a suboptimal thing.  It's usually troublesome in the event that extra work that was done gives rise to system, team, or individual developer issues and you can't find a record of why it was done.
