### ISSUE TITLE
Change documentation around reviewing PRs

### ISSUE THREAD

**Issue by javpet** [AgileVentures/sfn-client#229]
The current documentation of reviewing PRs is not 100% complete.

## Expected Behavior

If someone is following the original documentation of how to check another contributor's PR, might be quickly face an issue after pulling down the upstream branch that the opened PR's number is not there.

The expected behavior from the documentation is to specify the use case when someone is opening a PR from the forked repo.

## Current Behavior

The current documentation only handles the case when the PR has been merged into the develop branch, so the reviewer can test it locally by doing `git fetch upstream`

## Possible Solution

Adding the use case to the documentation if someone is checking some else's PR, who made the PR from a forked repo.

**Comment by FedericoEsparza** [comment]
@javpet This is already documented here: https://github.com/AgileVentures/sfn-client/blob/develop/HOW-TO-REVIEW-A-DEVELOP-PR.md#for-forked-repos

And linked from the very first line:
<img width="838" alt="Screen Shot 2019-05-12 at 12 18 57 AM" src="https://user-images.githubusercontent.com/11988089/57578132-12177180-7476-11e9-9949-6b9cc5c7103e.png">


**Do you think this needs improvement, so that it's more clear?**

**Comment by javpet** [comment]
Sorry @aonomike has pointed out this yesterday, I'll close the ticket as we won't do. 
Maybe what was misleading at first is that it's in an unless + () so it felt secondary message, meanwhile probably this a more typical use case.

**Comment by FedericoEsparza** [comment]
Ok. Thanks @javpet. 

Thanks to @mhobesong , we did update the README to encourage people to push their branches and make their PRs on upstream: https://github.com/AgileVentures/sfn-client#pull-requests

So the default case should, hopefully, be the one at the top fo the doc, more, going forward.
