### ISSUE TITLE
Change cause card to receive cause prop

### ISSUE THREAD

**Issue by aonomike** [AgileVentures/sfn-client#447]
The cause card currently receives props from attributes of the cause object. I would be nice to refactor so that it just receives the cause object, which has the cause attributes.
## Expected Behavior

The cause object is passed to the cause card as below
```
<CauseCard cause={cause}/>
```

## Current Behavior

The Cause card receives attributes of the cause object as below
```
<CauseCard name = {cause.name} description={cause.description} targetAmount={cause.targetAmount} />
```
## Possible Solution

Pass the cause as an object to the cause card

**Comment by yakryder** [comment]
^^Not a refactor of the Cause Card. Its public API is changing.

These days I still worry that I'll put my foot in my mouth when it comes to React. But on the surface this seems like a smart idea 👍

**Comment by yakryder** [comment]
You could consider this a refactor of the Cause index view, Cause show view, etc., because you are changing how those views work without changing how they behave. But you are changing how a CauseCard interacts with its collaborators, therefore it is a CauseCard change.

See also discussion for
#145 
#173

**Comment by aonomike** [comment]
Thanks @SherSpock very well noted
