### ISSUE TITLE
Create individual performance component 

### ISSUE THREAD

**Issue by javpet** [AgileVentures/sfn-client#57]
The individual performance item elements will be part of the performances component.

**Comment by javpet** [comment]
Limit the number of performances to most recent 3.

**Comment by FedericoEsparza** [comment]
Thanks, Peter.
 
Let's call this component `Performance`, since we're going with PerformanceContainer for the "show" page container, in Rails/Phoenix lingo (to avoid confusion).
 
Even though the component will probably be used in both the `Performance/` and the `Performances/` pages/containers, let's put it in the *Performance* (singular) folder.

**Comment by FedericoEsparza** [comment]
Thinking about this. I think you were referring to the Performances in the ArtistContainer:
![Screenshot 2019-02-10 10.22.31.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57e387b76082a50f00d31003/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1cd6416753e7854e37a20cbb17af1112a43434d0eee1e020a17b8eb8339a3e53f718b5c59ebd9385f75c43f11aebd851cbf01bf21da5d99a4fedb1294b7607caddecd5d340c041f83fe5831a9914ace58f149e64e5cb65e.png)

Let's call this individual component `ArtistPerformance` and put it in the `Artist/` folder.

**Comment by javpet** [comment]
@FedericoEsparza we kinda afraid to merge this in without your permission. :)
